openapi: 3.2.0
info:
  description: The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas.
  license:
    name: CC BY-NC-SA 3.0 US
    url: https://creativecommons.org/licenses/by-nc-sa/3.0/us/
  termsOfService: https://www.mongodb.com/mongodb-management-service-terms-and-conditions
  title: MongoDB Atlas Administration AI Model Rate Limits API
  version: '2.0'
  x-xgen-sha: 8f9485d239f53f5b963c55e11f5f05a34bec9586
servers:
- url: https://cloud.mongodb.com
security:
- ServiceAccounts: []
- DigestAuth: []
tags:
- description: Returns, adds, edits, and removes Rate Limits for your AI Models.
  name: AI Model Rate Limits
paths:
  ? /api/atlas/v2/groups/{groupId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits
  : get:
      description: Retrieve a single scoped AI model rate limit for the given group.
      operationId: getGroupAiModelApiCloudGeographyModelGroupNameRateLimits
      parameters:
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - description: Cloud provider scope. Must be "ANY". Additional values will be supported in future API versions.
        in: path
        name: cloud
        required: true
        schema:
          enum:
          - ANY
          type: string
      - description: Geography scope. Must be "ANY". Additional values will be supported in future API versions.
        in: path
        name: geography
        required: true
        schema:
          enum:
          - ANY
          type: string
      - description: The name of the model group to be retrieved.
        in: path
        name: modelGroupName
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/vnd.atlas.2025-03-12+json:
              schema:
                $ref: '#/components/schemas/AiModelRateLimitResponse'
              x-xgen-version: '2025-03-12'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/HeaderRateLimitLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/HeaderRateLimitRemaining'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '429':
          $ref: '#/components/responses/tooManyRequests'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Return Single AI Model Rate Limit for One Group
      tags:
      - AI Model Rate Limits
      x-codeSamples:
      - label: Atlas CLI
        lang: cURL
        source: atlas api aiModelRateLimits getGroupRateLimits --help
      - label: Go
        lang: go
        source: "import (\n\t\"os\"\n\t\"context\"\n\t\"log\"\n\tsdk \"go.mongodb.org/atlas-sdk/v20250312001/admin\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tclientID := os.Getenv(\"MONGODB_ATLAS_CLIENT_ID\")\n\tclientSecret := os.Getenv(\"MONGODB_ATLAS_CLIENT_SECRET\")\n\n\t// See https://dochub.mongodb.org/core/atlas-go-sdk-oauth\n\tclient, err := sdk.NewClient(sdk.UseOAuthAuth(clientID, clientSecret))\n\n\tif err != nil {\n\t\tlog.Fatalf(\"Error: %v\", err)\n\t}\n\n\tparams = &sdk.GetGroupAiModelApiCloudGeographyModelGroupNameRateLimitsApiParams{}\n\tsdkResp, httpResp, err := client.AIModelRateLimitsApi.\n\t\tGetGroupAiModelApiCloudGeographyModelGroupNameRateLimitsWithParams(ctx, params).\n\t\tExecute()\n}\n"
      - label: curl (Service Accounts)
        lang: cURL
        source: "curl --include --header \"Authorization: Bearer ${ACCESS_TOKEN}\" \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits?pretty=true\""
      - label: curl (Digest)
        lang: cURL
        source: "curl --user \"${PUBLIC_KEY}:${PRIVATE_KEY}\" \\\n  --digest --include \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits?pretty=true\""
      x-rolesRequirements:
      - Project Read Only
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/AI-Model-Rate-Limits/operation/getGroupAiModelApiCloudGeographyModelGroupNameRateLimits
      x-xgen-operation-id-override: getGroupRateLimits
    patch:
      description: Update a scoped AI model rate limit for the given model group.
      operationId: updateGroupAiModelApiCloudGeographyModelGroupNameRateLimits
      parameters:
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - description: Cloud provider scope. Must be "ANY". Additional values will be supported in future API versions.
        in: path
        name: cloud
        required: true
        schema:
          enum:
          - ANY
          type: string
      - description: Geography scope. Must be "ANY". Additional values will be supported in future API versions.
        in: path
        name: geography
        required: true
        schema:
          enum:
          - ANY
          type: string
      - description: The name of the model group to be updated.
        in: path
        name: modelGroupName
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/vnd.atlas.2025-03-12+json:
            schema:
              $ref: '#/components/schemas/AiModelsRateLimitUpdateRequest'
            x-xgen-version: '2025-03-12'
        description: A request containing the new rate limits for the given model group.
        required: true
      responses:
        '200':
          content:
            application/vnd.atlas.2025-03-12+json:
              schema:
                $ref: '#/components/schemas/AiModelRateLimitResponse'
              x-xgen-version: '2025-03-12'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/HeaderRateLimitLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/HeaderRateLimitRemaining'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '429':
          $ref: '#/components/responses/tooManyRequests'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Update AI Model Rate Limit
      tags:
      - AI Model Rate Limits
      x-codeSamples:
      - label: Atlas CLI
        lang: cURL
        source: atlas api aiModelRateLimits updateGroupRateLimits --help
      - label: Go
        lang: go
        source: "import (\n\t\"os\"\n\t\"context\"\n\t\"log\"\n\tsdk \"go.mongodb.org/atlas-sdk/v20250312001/admin\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tclientID := os.Getenv(\"MONGODB_ATLAS_CLIENT_ID\")\n\tclientSecret := os.Getenv(\"MONGODB_ATLAS_CLIENT_SECRET\")\n\n\t// See https://dochub.mongodb.org/core/atlas-go-sdk-oauth\n\tclient, err := sdk.NewClient(sdk.UseOAuthAuth(clientID, clientSecret))\n\n\tif err != nil {\n\t\tlog.Fatalf(\"Error: %v\", err)\n\t}\n\n\tparams = &sdk.UpdateGroupAiModelApiCloudGeographyModelGroupNameRateLimitsApiParams{}\n\tsdkResp, httpResp, err := client.AIModelRateLimitsApi.\n\t\tUpdateGroupAiModelApiCloudGeographyModelGroupNameRateLimitsWithParams(ctx, params).\n\t\tExecute()\n}\n"
      - label: curl (Service Accounts)
        lang: cURL
        source: "curl --include --header \"Authorization: Bearer ${ACCESS_TOKEN}\" \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  --header \"Content-Type: application/json\" \\\n  -X PATCH \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits\" \\\n  -d '{ <Payload> }'"
      - label: curl (Digest)
        lang: cURL
        source: "curl --user \"${PUBLIC_KEY}:${PRIVATE_KEY}\" \\\n  --digest --include \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  --header \"Content-Type: application/json\" \\\n  -X PATCH \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits\" \\\n  -d '{ <Payload> }'"
      x-rolesRequirements:
      - Project Model Owner
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/AI-Model-Rate-Limits/operation/updateGroupAiModelApiCloudGeographyModelGroupNameRateLimits
      x-xgen-operation-id-override: updateGroupRateLimits
  ? /api/atlas/v2/groups/{groupId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits:reset
  : post:
      description: Reset the scoped AI model rate limit for the given model group to default values.
      operationId: resetGroupAiModelApiCloudGeographyModelGroupNameRateLimits
      parameters:
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - description: Cloud provider scope. Must be "ANY". Additional values will be supported in future API versions.
        in: path
        name: cloud
        required: true
        schema:
          enum:
          - ANY
          type: string
      - description: Geography scope. Must be "ANY". Additional values will be supported in future API versions.
        in: path
        name: geography
        required: true
        schema:
          enum:
          - ANY
          type: string
      - description: The name of the model group to be reset to default rate limits.
        in: path
        name: modelGroupName
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/vnd.atlas.2025-03-12+json:
              schema:
                $ref: '#/components/schemas/AiModelRateLimitResponse'
              x-xgen-version: '2025-03-12'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/HeaderRateLimitLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/HeaderRateLimitRemaining'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '429':
          $ref: '#/components/responses/tooManyRequests'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Reset AI Model Rate Limit for One Model Group
      tags:
      - AI Model Rate Limits
      x-codeSamples:
      - label: Atlas CLI
        lang: cURL
        source: atlas api aiModelRateLimits resetGroupModelLimits --help
      - label: Go
        lang: go
        source: "import (\n\t\"os\"\n\t\"context\"\n\t\"log\"\n\tsdk \"go.mongodb.org/atlas-sdk/v20250312001/admin\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tclientID := os.Getenv(\"MONGODB_ATLAS_CLIENT_ID\")\n\tclientSecret := os.Getenv(\"MONGODB_ATLAS_CLIENT_SECRET\")\n\n\t// See https://dochub.mongodb.org/core/atlas-go-sdk-oauth\n\tclient, err := sdk.NewClient(sdk.UseOAuthAuth(clientID, clientSecret))\n\n\tif err != nil {\n\t\tlog.Fatalf(\"Error: %v\", err)\n\t}\n\n\tparams = &sdk.ResetGroupAiModelApiCloudGeographyModelGroupNameRateLimitsApiParams{}\n\tsdkResp, httpResp, err := client.AIModelRateLimitsApi.\n\t\tResetGroupAiModelApiCloudGeographyModelGroupNameRateLimitsWithParams(ctx, params).\n\t\tExecute()\n}\n"
      - label: curl (Service Accounts)
        lang: cURL
        source: "curl --include --header \"Authorization: Bearer ${ACCESS_TOKEN}\" \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  --header \"Content-Type: application/json\" \\\n  -X POST \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits:reset\" \\\n  -d '{ <Payload> }'"
      - label: curl (Digest)
        lang: cURL
        source: "curl --user \"${PUBLIC_KEY}:${PRIVATE_KEY}\" \\\n  --digest --include \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  --header \"Content-Type: application/json\" \\\n  -X POST \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits:reset\" \\\n  -d '{ <Payload> }'"
      x-rolesRequirements:
      - Project Model Owner
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/AI-Model-Rate-Limits/operation/resetGroupAiModelApiCloudGeographyModelGroupNameRateLimits
      x-xgen-operation-id-override: resetGroupModelLimits
  /api/atlas/v2/groups/{groupId}/aiModelApiRateLimits:
    get:
      description: Retrieve AI model rate limits for the given group.
      operationId: getGroupAiModelApiRateLimits
      parameters:
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/itemsPerPage'
      - $ref: '#/components/parameters/pageNum'
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          content:
            application/vnd.atlas.2025-03-12+json:
              schema:
                $ref: '#/components/schemas/PaginatedAtlasAiModelRateLimitsResponse'
              x-xgen-version: '2025-03-12'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/HeaderRateLimitLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/HeaderRateLimitRemaining'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '429':
          $ref: '#/components/responses/tooManyRequests'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Return AI Model Rate Limits for One Group
      tags:
      - AI Model Rate Limits
      x-codeSamples:
      - label: Atlas CLI
        lang: cURL
        source: atlas api aiModelRateLimits getGroupModelLimits --help
      - label: Go
        lang: go
        source: "import (\n\t\"os\"\n\t\"context\"\n\t\"log\"\n\tsdk \"go.mongodb.org/atlas-sdk/v20250312001/admin\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tclientID := os.Getenv(\"MONGODB_ATLAS_CLIENT_ID\")\n\tclientSecret := os.Getenv(\"MONGODB_ATLAS_CLIENT_SECRET\")\n\n\t// See https://dochub.mongodb.org/core/atlas-go-sdk-oauth\n\tclient, err := sdk.NewClient(sdk.UseOAuthAuth(clientID, clientSecret))\n\n\tif err != nil {\n\t\tlog.Fatalf(\"Error: %v\", err)\n\t}\n\n\tparams = &sdk.GetGroupAiModelApiRateLimitsApiParams{}\n\tsdkResp, httpResp, err := client.AIModelRateLimitsApi.\n\t\tGetGroupAiModelApiRateLimitsWithParams(ctx, params).\n\t\tExecute()\n}\n"
      - label: curl (Service Accounts)
        lang: cURL
        source: "curl --include --header \"Authorization: Bearer ${ACCESS_TOKEN}\" \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiRateLimits?pretty=true\""
      - label: curl (Digest)
        lang: cURL
        source: "curl --user \"${PUBLIC_KEY}:${PRIVATE_KEY}\" \\\n  --digest --include \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiRateLimits?pretty=true\""
      x-rolesRequirements:
      - Project Read Only
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/AI-Model-Rate-Limits/operation/getGroupAiModelApiRateLimits
      x-xgen-operation-id-override: getGroupModelLimits
  /api/atlas/v2/groups/{groupId}/aiModelApiRateLimits:reset:
    post:
      description: Reset the AI Model rate limits for the given group to default values.
      operationId: resetGroupAiModelApiRateLimits
      parameters:
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          content:
            application/vnd.atlas.2025-03-12+json:
              schema:
                $ref: '#/components/schemas/PaginatedAtlasAiModelRateLimitsResponse'
              x-xgen-version: '2025-03-12'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/HeaderRateLimitLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/HeaderRateLimitRemaining'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '429':
          $ref: '#/components/responses/tooManyRequests'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Reset AI Model Rate Limits for Group
      tags:
      - AI Model Rate Limits
      x-codeSamples:
      - label: Atlas CLI
        lang: cURL
        source: atlas api aiModelRateLimits resetGroupRateLimits --help
      - label: Go
        lang: go
        source: "import (\n\t\"os\"\n\t\"context\"\n\t\"log\"\n\tsdk \"go.mongodb.org/atlas-sdk/v20250312001/admin\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tclientID := os.Getenv(\"MONGODB_ATLAS_CLIENT_ID\")\n\tclientSecret := os.Getenv(\"MONGODB_ATLAS_CLIENT_SECRET\")\n\n\t// See https://dochub.mongodb.org/core/atlas-go-sdk-oauth\n\tclient, err := sdk.NewClient(sdk.UseOAuthAuth(clientID, clientSecret))\n\n\tif err != nil {\n\t\tlog.Fatalf(\"Error: %v\", err)\n\t}\n\n\tparams = &sdk.ResetGroupAiModelApiRateLimitsApiParams{}\n\tsdkResp, httpResp, err := client.AIModelRateLimitsApi.\n\t\tResetGroupAiModelApiRateLimitsWithParams(ctx, params).\n\t\tExecute()\n}\n"
      - label: curl (Service Accounts)
        lang: cURL
        source: "curl --include --header \"Authorization: Bearer ${ACCESS_TOKEN}\" \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  --header \"Content-Type: application/json\" \\\n  -X POST \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiRateLimits:reset\" \\\n  -d '{ <Payload> }'"
      - label: curl (Digest)
        lang: cURL
        source: "curl --user \"${PUBLIC_KEY}:${PRIVATE_KEY}\" \\\n  --digest --include \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  --header \"Content-Type: application/json\" \\\n  -X POST \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/aiModelApiRateLimits:reset\" \\\n  -d '{ <Payload> }'"
      x-rolesRequirements:
      - Project Model Owner
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/AI-Model-Rate-Limits/operation/resetGroupAiModelApiRateLimits
      x-xgen-method-verb-override:
        customMethod: 'True'
        verb: reset
      x-xgen-operation-id-override: resetGroupRateLimits
  /api/atlas/v2/orgs/{orgId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits:
    get:
      description: Retrieve a single scoped AI model rate limit for the given organization.
      operationId: getOrgAiModelApiCloudGeographyModelGroupNameRateLimits
      parameters:
      - $ref: '#/components/parameters/orgId'
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - description: Cloud provider scope. Must be "ANY". Additional values will be supported in future API versions.
        in: path
        name: cloud
        required: true
        schema:
          enum:
          - ANY
          type: string
      - description: Geography scope. Must be "ANY". Additional values will be supported in future API versions.
        in: path
        name: geography
        required: true
        schema:
          enum:
          - ANY
          type: string
      - description: The name of the model group to be retrieved.
        in: path
        name: modelGroupName
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/vnd.atlas.2025-03-12+json:
              schema:
                $ref: '#/components/schemas/AiModelRateLimitResponse'
              x-xgen-version: '2025-03-12'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/HeaderRateLimitLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/HeaderRateLimitRemaining'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '429':
          $ref: '#/components/responses/tooManyRequests'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Return Single AI Model Rate Limit for One Organization
      tags:
      - AI Model Rate Limits
      x-codeSamples:
      - label: Atlas CLI
        lang: cURL
        source: atlas api aiModelRateLimits getOrgRateLimits --help
      - label: Go
        lang: go
        source: "import (\n\t\"os\"\n\t\"context\"\n\t\"log\"\n\tsdk \"go.mongodb.org/atlas-sdk/v20250312001/admin\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tclientID := os.Getenv(\"MONGODB_ATLAS_CLIENT_ID\")\n\tclientSecret := os.Getenv(\"MONGODB_ATLAS_CLIENT_SECRET\")\n\n\t// See https://dochub.mongodb.org/core/atlas-go-sdk-oauth\n\tclient, err := sdk.NewClient(sdk.UseOAuthAuth(clientID, clientSecret))\n\n\tif err != nil {\n\t\tlog.Fatalf(\"Error: %v\", err)\n\t}\n\n\tparams = &sdk.GetOrgAiModelApiCloudGeographyModelGroupNameRateLimitsApiParams{}\n\tsdkResp, httpResp, err := client.AIModelRateLimitsApi.\n\t\tGetOrgAiModelApiCloudGeographyModelGroupNameRateLimitsWithParams(ctx, params).\n\t\tExecute()\n}\n"
      - label: curl (Service Accounts)
        lang: cURL
        source: "curl --include --header \"Authorization: Bearer ${ACCESS_TOKEN}\" \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits?pretty=true\""
      - label: curl (Digest)
        lang: cURL
        source: "curl --user \"${PUBLIC_KEY}:${PRIVATE_KEY}\" \\\n  --digest --include \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/aiModelApiClouds/{cloud}/geographies/{geography}/modelGroupNames/{modelGroupName}/rateLimits?pretty=true\""
      x-rolesRequirements:
      - Organization Read Only
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/AI-Model-Rate-Limits/operation/getOrgAiModelApiCloudGeographyModelGroupNameRateLimits
      x-xgen-operation-id-override: getOrgRateLimits
  /api/atlas/v2/orgs/{orgId}/aiModelApiRateLimits:
    get:
      description: Retrieve AI model rate limits for the given organization.
      operationId: getOrgAiModelApiRateLimits
      parameters:
      - $ref: '#/components/parameters/orgId'
      - $ref: '#/components/parameters/itemsPerPage'
      - $ref: '#/components/parameters/pageNum'
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          content:
            application/vnd.atlas.2025-03-12+json:
              schema:
                $ref: '#/components/schemas/PaginatedAtlasAiModelRateLimitsResponse'
              x-xgen-version: '2025-03-12'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/HeaderRateLimitLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/HeaderRateLimitRemaining'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '429':
          $ref: '#/components/responses/tooManyRequests'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Return AI Model Rate Limits for One Organization
      tags:
      - AI Model Rate Limits
      x-codeSamples:
      - label: Atlas CLI
        lang: cURL
        source: atlas api aiModelRateLimits getOrgModelLimits --help
      - label: Go
        lang: go
        source: "import (\n\t\"os\"\n\t\"context\"\n\t\"log\"\n\tsdk \"go.mongodb.org/atlas-sdk/v20250312001/admin\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tclientID := os.Getenv(\"MONGODB_ATLAS_CLIENT_ID\")\n\tclientSecret := os.Getenv(\"MONGODB_ATLAS_CLIENT_SECRET\")\n\n\t// See https://dochub.mongodb.org/core/atlas-go-sdk-oauth\n\tclient, err := sdk.NewClient(sdk.UseOAuthAuth(clientID, clientSecret))\n\n\tif err != nil {\n\t\tlog.Fatalf(\"Error: %v\", err)\n\t}\n\n\tparams = &sdk.GetOrgAiModelApiRateLimitsApiParams{}\n\tsdkResp, httpResp, err := client.AIModelRateLimitsApi.\n\t\tGetOrgAiModelApiRateLimitsWithParams(ctx, params).\n\t\tExecute()\n}\n"
      - label: curl (Service Accounts)
        lang: cURL
        source: "curl --include --header \"Authorization: Bearer ${ACCESS_TOKEN}\" \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/aiModelApiRateLimits?pretty=true\""
      - label: curl (Digest)
        lang: cURL
        source: "curl --user \"${PUBLIC_KEY}:${PRIVATE_KEY}\" \\\n  --digest --include \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/aiModelApiRateLimits?pretty=true\""
      x-rolesRequirements:
      - Organization Read Only
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/AI-Model-Rate-Limits/operation/getOrgAiModelApiRateLimits
      x-xgen-operation-id-override: getOrgModelLimits
components:
  parameters:
    envelope:
      description: Flag that indicates whether Application wraps the response in an `envelope` JSON object. Some API clients cannot access the HTTP response headers or status code. To remediate this, set envelope=true in the query. Endpoints that return a list of results use the results object as an envelope. Application adds the status parameter to the response body.
      in: query
      name: envelope
      schema:
        default: false
        type: boolean
    itemsPerPage:
      description: Number of items that the response returns per page.
      in: query
      name: itemsPerPage
      schema:
        default: 100
        maximum: 500
        minimum: 1
        type: integer
    pretty:
      description: Flag that indicates whether the response body should be in the prettyprint format.
      in: query
      name: pretty
      schema:
        default: false
        externalDocs:
          description: Prettyprint
          url: https://en.wikipedia.org/wiki/Prettyprint
        type: boolean
    pageNum:
      description: Number of the page that displays the current set of the total objects that the response returns.
      in: query
      name: pageNum
      schema:
        default: 1
        minimum: 1
        type: integer
    orgId:
      description: Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.
      in: path
      name: orgId
      required: true
      schema:
        example: 4888442a3354817a7320eb61
        pattern: ^([a-f0-9]{24})$
        type: string
    groupId:
      description: 'Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.


        **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.'
      in: path
      name: groupId
      required: true
      schema:
        example: 32b6e34b3d91647abb20e7b8
        pattern: ^([a-f0-9]{24})$
        type: string
  schemas:
    FieldViolation:
      properties:
        description:
          description: A description of why the request element is bad.
          type: string
        field:
          description: A path that leads to a field in the request body.
          type: string
      required:
      - description
      - field
      type: object
    AiModelRateLimitResponse:
      properties:
        cloud:
          description: Cloud provider scope for this rate limit. Use "ANY" for cloud-agnostic scope.
          example: ANY
          readOnly: true
          type: string
        endpoint:
          description: Server-computed endpoint hostname derived from `cloud` and `geography`. This field is read-only and must not be supplied in request bodies.
          example: ai.mongodb.com
          readOnly: true
          type: string
        geography:
          description: Geography scope for this rate limit. Use "ANY" for geography-agnostic scope.
          example: ANY
          readOnly: true
          type: string
        modelGroupName:
          description: Identifier used to reference this model group.
          example: embed_large
          readOnly: true
          type: string
        modelNames:
          description: List of embedding model names included in this model group.
          items:
            type: string
          maxItems: 100
          readOnly: true
          type: array
        requestsPerMinuteLimit:
          description: The number of requests per minute allowed for this model group. Must be a positive integer. Cannot be more than the organization level limit for this group model.
          example: 2000
          format: int32
          minimum: 1
          type: integer
        tokensPerMinuteLimit:
          description: The number of tokens per minute allowed for this model group. Must be a positive integer. Cannot be more than the organization level limit for this group model.
          example: 3e+06
          format: int32
          minimum: 1
          type: integer
      type: object
    PaginatedAtlasAiModelRateLimitsResponse:
      description: List response for AI Model rate limits at the organization and project level.
      properties:
        links:
          description: List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
          externalDocs:
            description: Web Linking Specification (RFC 5988)
            url: https://datatracker.ietf.org/doc/html/rfc5988
          items:
            $ref: '#/components/schemas/Link'
          readOnly: true
          type: array
        results:
          description: List of returned documents that MongoDB Cloud provides when completing this request.
          items:
            $ref: '#/components/schemas/AiModelRateLimitResponse'
          readOnly: true
          type: array
        totalCount:
          description: Total number of documents available. When `includeCount` is set to `false`, MongoDB Cloud may omit this value or return it when the count is available without additional calculation. The total number is an estimate and may not be exact.
          format: int32
          minimum: 0
          readOnly: true
          type: integer
      required:
      - results
      type: object
    Link:
      properties:
        href:
          description: Uniform Resource Locator (URL) that points another API resource to which this response has some relationship. This URL often begins with `https://cloud.mongodb.com/api/atlas`.
          example: https://cloud.mongodb.com/api/atlas
          type: string
        rel:
          description: Uniform Resource Locator (URL) that defines the semantic relationship between this resource and another API resource. This URL often begins with `https://cloud.mongodb.com/api/atlas`.
          example: self
          type: string
      type: object
    AiModelsRateLimitUpdateRequest:
      properties:
        requestsPerMinuteLimit:
          description: The number of requests per minute allowed for this model group. Must be a positive integer. Cannot be more than the organization level limit for this group model.
          format: int32
          minimum: 1
          type: integer
        tokensPerMinuteLimit:
          description: The number of tokens per minute allowed for this model group. Must be a positive integer. Cannot be more than the organization level limit for this group model.
          format: int32
          minimum: 1
          type: integer
      required:
      - requestsPerMinuteLimit
      - tokensPerMinuteLimit
      type: object
    ApiError:
      properties:
        badRequestDetail:
          $ref: '#/components/schemas/BadRequestDetail'
        detail:
          description: Describes the specific conditions or reasons that cause each type of error.
          type:
          - string
          - 'null'
        error:
          description: HTTP status code returned with this error.
          externalDocs:
            url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
          format: int32
          readOnly: true
          type: integer
        errorCode:
          description: Application error code returned with this error.
          readOnly: true
          type: string
        parameters:
          description: Parameters used to give more information about the error.
          items:
            type: object
          readOnly: true
          type: array
        reason:
          description: Application error message returned with this error.
          readOnly: true
          type:
          - string
          - 'null'
      required:
      - error
      - errorCode
      type: object
    BadRequestDetail:
      description: Bad request detail.
      properties:
        fields:
          description: Describes all violations in a client request.
          items:
            $ref: '#/components/schemas/FieldViolation'
          type: array
      readOnly: true
      type: object
  headers:
    HeaderRateLimitRemaining:
      description: The number of requests remaining in the current rate limit window before the limit is reached.
      schema:
        type: integer
    HeaderRateLimitLimit:
      description: The maximum number of requests that a user can make within a specific time window.
      schema:
        type: integer
    HeaderRetryAfter:
      description: The minimum time you should wait, in seconds, before retrying the API request. This header might be returned for 429 or 503 error responses.
      schema:
        type: integer
  responses:
    unauthorized:
      content:
        application/json:
          example:
            detail: (This is just an example, the exception may not be related to this endpoint)
            error: 401
            errorCode: NOT_ORG_GROUP_CREATOR
            reason: Unauthorized
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Unauthorized.
    forbidden:
      content:
        application/json:
          example:
            detail: (This is just an example, the exception may not be related to this endpoint)
            error: 403
            errorCode: CANNOT_CHANGE_GROUP_NAME
            reason: Forbidden
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Forbidden.
    notFound:
      content:
        application/json:
          example:
            detail: (This is just an example, the exception may not be related to this endpoint) Cannot find resource AWS
            error: 404
            errorCode: RESOURCE_NOT_FOUND
            reason: Not Found
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Not Found.
    tooManyRequests:
      content:
        application/json:
          example:
            detail: (This is just an example, the exception may not be related to this endpoint)
            error: 429
            errorCode: RATE_LIMITED
            reason: Too Many Requests
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Too Many Requests.
      headers:
        RateLimit-Limit:
          $ref: '#/components/headers/HeaderRateLimitLimit'
        RateLimit-Remaining:
          $ref: '#/components/headers/HeaderRateLimitRemaining'
        Retry-After:
          $ref: '#/components/headers/HeaderRetryAfter'
    internalServerError:
      content:
        application/json:
          example:
            detail: (This is just an example, the exception may not be related to this endpoint)
            error: 500
            errorCode: UNEXPECTED_ERROR
            reason: Internal Server Error
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Internal Server Error.
    badRequest:
      content:
        application/json:
          example:
            detail: (This is just an example, the exception may not be related to this endpoint) No provider AWS exists.
            error: 400
            errorCode: VALIDATION_ERROR
            reason: Bad Request
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Bad Request.
  securitySchemes:
    DigestAuth:
      scheme: digest
      type: http
    ServiceAccounts:
      description: Learn more about [Service Accounts](https://www.mongodb.com/docs/atlas/api/service-accounts-overview).
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://cloud.mongodb.com/api/oauth/token
      type: oauth2
x-externalLinks:
- label: Back to Atlas Docs
  url: https://www.mongodb.com/docs/atlas/
- label: API Changelog
  url: https://www.mongodb.com/docs/atlas/reference/api-resources-spec/changelog/
x-topics:
- content: The MongoDB Atlas Administration API is rate limited. To learn more about rate limiting, see the [Atlas Documentation on Rate Limiting](http://dochub.mongodb.org/core/atlas-api-rate-limit)
  title: Rate Limiting
